module.exports = {
    token: {
        TOKEN_EXPIRE_TIME: 900, 
    },
    cache: {
        CACHE_EXPIRE_TIME: 60,  
    },
    statusMessage: {
        PERMISSION_DENIED: "PERMISSION_DENIED",
        INVALID_USERNAME_OR_PASSWORD: "INVALID_USERNAME_OR_PASSWORD",
        USERNAME_ALREADY_EXIST: "USERNAME_ALREADY_EXIST",
        EMAIL_ALREADY_EXIST: "EMAIL_ALREADY_EXIST",
        PRODUCT_ALREADY_EXIST: "PRODUCT_ALREADY_EXIST",
        PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",
        CATEGORY_ALREADY_EXIST: "CATEGORY_ALREADY_EXIST",
        BAD_REQUEST: "BAD_REQUEST",
        USER_NOT_FOUND: "USER_NOT_FOUND",
        INVALID_USER_ID: "INVALID_USER_ID",
        ALL_FIELDS_NEED_REQUIRED: "ALL_FIELDS_NEED_REQUIRED",
    },
    role: {
        ADMIN_ROLE: "ADMIN",
        USER_ROLE: "USER",
    },
    ELASTICSEARCH_NODE: process.env.ELASTICSEARCH_NODE,
    STRIPE_ENDPOINT: process.env.STRIPE_ENDPOINT,
    STRIPE_PUBLISH_KEY: process.env.STRIPE_PUBLISHABLE_KEY,
    STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
    PORT: process.env.PORT,
    JWT: process.env.TOKEN_KEY,
    MONGODB: process.env.MONGODB
}